version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 0 # disable non-security updates
  - package-ecosystem: "npm"
    directory: "/modules/backend"
    schedule:
      interval: "daily"
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 0 # disable non-security updates
  - package-ecosystem: "npm"
    directory: "/modules/frontend"
    schedule:
      interval: "daily"
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 0 # disable non-security updates
