name = "genshin-translate"
type = "webpack"

account_id = "8306a13fafb28ed9cc9c2effe76f7830"
zone_id = "a09b7e4a6472f3505dce22284b12dc6e"
workers_dev = false
compatibility_date = "2022-04-17"

[env.production]
route = "translate-backend.genshin-dictionary.com/*"

[env.production.vars]
SERVER_ENV = "production"

[env.preview]
route = "translate-backend-preview.genshin-dictionary.com/*"

[env.preview.vars]
SERVER_ENV = "preview"

[env.development]
workers_dev = true

[env.development.vars]
SERVER_ENV = "development"

# [secrets]
# MINHON_API_KEY
# MINHON_API_SECRET
# MINHON_LOGIN_ID
